name: pr

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  UE_ROOT: ${{ vars.UE_ROOT }}
  WORKDIR: ${{ vars.WORKDIR }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: build
        shell: powershell -ExecutionPolicy Bypass -Command "{0}"
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          git config --global --add safe.directory "$env:WORKDIR"
          Set-Location "$env:WORKDIR"
          pwd
          git pull
          .\Scripts\BuildObriy.ps1 -Actions PackArchive -Configuration Development
