name: pr

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

env:
  UE_ROOT: ${{ vars.UE_ROOT }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: build
        shell: powershell -ExecutionPolicy Bypass -Command "{0}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $repoName = ($env:GITHUB_REPOSITORY -split '/')[1]
          $workDir = Join-Path "G:\" $repoName
          git config --global --add safe.directory "$workDir"
          Set-Location "$workDir"
          pwd
          whoami
          git remote set-url origin "https://x-access-token:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git"
          git pull
#          if ($LASTEXITCODE -ne 0) { throw "git pull failed" }
#          .\Scripts\BuildObriy.ps1 -Actions PackArchive -Configuration Development
